source/PmmEdit/codeeditor.cpp
Missed spot where text color is set for no. of cycles (actual integer value), it was hardcoded to yellow. This fix will follow theme setting.
=> Cycles text color no longer hardcoded to yellow

imageeditor.cpp
Undo functionality in character editor crashes when built with clang. The code could be simplified a bit too, and calling delete to QVector causes the crash.
=> Fix Undo in character editor

resources/text/syntax.txt, source/Compiler/assembler/methods6502.cpp, source/Compiler/assembler/methods6502.h, source/Compiler/parser.cpp
VIARasterIRQ() method added that takes 3 params: function, rasterline and pal/ntsc (0/1).
I will add help-texts as separate PR.
=> Add VIARasterIRQ() for VIC-20 raster interrupts

main.cpp, mainwindow.cpp, mainwindow.h
Something has been bothering me a while, which is, when opening TRSE, the window size and location is not remembered, instead it opens just maximized window. I'm using 28" monitor with high DPI and want to use multiple windows on same screen and resizing window is always tedious. 
This is suggested patch to remember user-set window size and location in TRSE.
=> Feature: Store and restore IDE window size

source/Compiler/assembler/mos6502/methods6502vic20.cpp, source/Compiler/assembler/mos6502/methods6502vic20.h, source/Compiler/parser.cpp
Previously when using the VBM commands to draw dots, blots or test pixels on the canvas, would share one INIT block. This resulted in a total of eight variants of the support methods added to the ASM file even if only one of them was needed.
This change separates each command with its own INIT support method making the ASM files produced that reference these commands smaller in size.
=> VBM Dot, Blot and TestPixel command insertion optimised

TRSE.pro
It seems Clang isn't that forgiving as GCC, while using the C++14 features. By default QMake sets the C++11 as a standard, but using auto in lambdas requires C++14 and Clang barfs without this setting.
=> Fix building on MacOS

resources/text/help/p/screen.rtf
=> Typo ("unexplanded")

source/dialogsplash.cpp
Setting the position to the center of parent on start.
=> Attempt to fix the off-center splash screen on windows

source/Compiler/assembler/mos6502/mos6502.cpp
The BASIC stub is now created correctly. I have tested on PET, Vic and C64. The two corrections are:
1. The address on the next line in BASIC is calculated correctly
2. The end of program is terminated correctly (extra zeros)
I've also commented the component part.
The new code is as follows:
```
// new method
Asm(".byte $00 ; fill $xxx0");
Asm( ".byte $" + QString::number( (Syntax::s.m_currentSystem->m_startAddress + 10) & 0x0ff, 16  ) + " ; lo byte of next line" );
Asm( ".byte $" + QString::number( ( (Syntax::s.m_currentSystem->m_startAddress + 10) & 0x0ff00 ) >> 8, 16 ) + " ; hi byte of next line" );
Asm(".byte $0a ; line 10");
Asm(".byte $00, $9e, $20 ; SYS token");
// write PETSCII / ASCII representation of address to call
Asm(intToHexString(Syntax::s.m_currentSystem->m_programStartAd …
```
=> Calculates the correct data for the BASIC stub

resources/text/help/r/pbmexport.rtf, source/LeLib/limage/multicolorimage.cpp
…for greater flexibility.
Can now export any number of columns / rows as an even pixel measurement (eg: 2, 4, 6, 8, 10 etc).
=> Updated PBMExport to work on pixel dimensions instead of characters

.gitignore
Add some generated files that are polluting git status output on linux.
Please confirm that it's OK to consider `moc_` and `ui_` prefixes as reserved for generated files.
=> Ignore most generated files on linux

source/PmmEdit/codeeditor.cpp
This fixes bug where shift-tab in editor also changes active UI element.
Fix is simple, just return from keyPressEvent() after handling Key_Backtab.
=> Bugfix: Shift-tab

source/PmmEdit/codeeditor.cpp
Tab/backtab indent broke undo into behaving really strangely.
This is a fix for it, also the selection expansion is made bit better.
In this same PR I also make autoindent-undo working more fluently.
=> Bugfix: Fix Undo in tab/backtab

TRSE.pro
Add bundle for Mac OS X deploy that can be enabled from command line by setting DEPLOY environment variable to "yes".
Doesn't affect other builds.
=> Feature: Add conditional bundle

source/PmmEdit/codeeditor.cpp
Very simple tiny PR. When using `begin` and there was already indented lines after that, it confused the auto begin-end -engine.
=> Fix a bug where Indent confused auto-begin-end

source/trsedocuments/trsedocument.cpp
Replacing `@prg` with prg file path, and then splitting it to parameters with a space key delimiter resulted in more (broken) parameters. i.e. with "D:\Documents\My TRSE Projects\main.prg" second parameter became "D:\Documents\My" instead of complete prg path.
This fix splits user-defined parameters first, then applies any changes to them (well there is only one at the moment - `@prg`).
Tested on Windows, please test it on other platforms.
Also i believe this feature could be expanded with more variables - like platform type, so the user-defined tool can process files properly without guessing a platform type from a file start address etc. (i.e. VIC-20 vs C64)
=> Allow spaces in PRG path for user defined tool (CTRL+T)

source/Compiler/systems/system65c816.cpp
CL65 defaults to -target C64, which does its own asciiz character manipulation. Target none leaves asciiz strings as is, and we can do our own modification in the printstring function. This fixes inverted text.
Fixes #679
=> Added Target None to CL65 commandline params

units/MEGA65/screen.tru
OR doesn't compile on CL65, ORA does.
Fixes #677
=> Set80ColumnMode() OR -> ORA

source/Compiler/systems/systemchip8.cpp
=> Wrong Start Address

.gitignore, source/Compiler/codegen/codegen_chip8.cpp, units/CHIP8/system/system.tru
Load store in Chip-8 acts more like ARM's LDM and STM.
From Cowgod's Documentation 
"
Fx55 - LD [I], Vx
Store registers V0 through Vx in memory starting at location I.
The interpreter copies the values of registers V0 through Vx into memory, starting at the address in I.
Fx65 - LD Vx, [I]
Read registers V0 through Vx from memory starting at location I.
The interpreter reads values from memory starting at location I into registers V0 through Vx.
"
I also added word loads and stores. Chip-8 is big endian so LD V1, [I] puts the high byte in V0 and the low byte in V1 and vica versa for stores. 
Edit: Oh I made an assumption in the library that the arguments are sequential in memory and you were unaware of it (due to the same weird load store semantics). I fixed it now.
=> Fixed load and store on Chip-8.

units/ATARI800/screen.tru
Current tab40 is an array of bytes, causing it to overflow and place strings erroneously over Y values of 6.
=> Fix Atari 800 tab40

.github/workflows/linux.yml, .github/workflows/macx.yml, .github/workflows/win32-msvc.yml, source/LeLib/data.cpp
@ghostsoft noticed the [nightly downloads](https://lemonspawn.com/turbo-rascal-syntax-error-expected-but-begin/downloads/) weren't working, so I updated all the failing GH actions to fix them.
Example: https://github.com/SupSuper/TRSE/releases/tag/nightly
Not sure why build failures remove the last download though, would be nice if old versions were kept around.
=> Fix nightly builds

units/PLUS4/input/key/implementation.ras
in its original form, it is confused with the joystick handling
=> fix plus4 keyboar query
