resources/text/syntax.txt
source/Compiler/assembler/methods6502.cpp
source/Compiler/assembler/methods6502.h
source/Compiler/parser.cpp

Here is an example program to tets the drawtextbox -feature. documentation follows soon.
program Boxer;
var
scr: array[25] of integer;
box: array[8] of byte = ($4f,$77,$50,$6a,$7a,$6f,$4c,$65);
@define scr_mem $0400
@define scr_width 40
@define scr_height 25
begin
createaddresstable(scr, @scr_mem, @scr_width, @scr_height);
drawtextbox(scr, box, 20, 10, 10, 8);
drawtextbox(scr, box, 15, 5, 10, 8);
loop();
end.

DrawTextBox() initial implementation

---

source/LeLib/util/util.cpp

Fix compile on mac

---

TRSE.pro
resources.qrc
resources/text/help/m/decrange.rtf
resources/text/help/m/incrange.rtf

incRange() and decRange() help

incrange and decrange help

---

source/dialoghelp.cpp

Added "procedure" as argument name for methods that are using procedure as argument.

Add text for procedure parameter type

---

resources/text/help/c/aux_color_and_volume.rtf
resources/text/help/c/hpen_register.rtf
resources/text/help/c/vic_data_loc.rtf
resources/text/help/c/vpen_register.rtf
resources/text/help/c/xpaddle_register.rtf
resources/text/help/c/ypaddle_register.rtf

Documentation for the main VIC (20) registers.

Main ViC register documentation.

---

source/trsedocuments/formpaw.cpp

In the PAW form, you can now specify either one or two files.  If one file is specified it works as previously.
Two files can now be specified by inserting a ; as a separator. This will create two output files, one for the incbin's (the first file) and one for the array (the second file).  This allows both to be included into the Turbo Rascal code separately which is useful when needing to use in different areas of memory.

PAW files now support export to two

---

TRSE.pro

This simple PR fixes the Mac build optimization mention in issue #425

Fix bug in TRSE.pro, Mac optimization

---

resources.qrc
resources/text/help/p/screen.rtf
resources/text/help/p/vbm_memory.rtf
resources/text/help/r/break.rtf
resources/text/help/r/continue.rtf
resources/text/help/r/return.rtf

Includes the break, continue and return. Some other minor updates.

Updated documentation

---

resources/text/help/p/variables.rtf

Typo: ```enemyx : array[4[ of integer;```

Replace [ with ]

---

resources/text/help/m/memcpy.rtf
resources/text/help/m/memcpyfast.rtf
resources/text/help/m/memcpyunroll.rtf

update memcpy help files

---

resources/text/help/m/copybytesshift.rtf

Update to CopyByteShift

---

resources/text/help/m/dec.rtf
resources/text/help/m/setspriteloc.rtf
resources/text/help/p/asm_tips.rtf
resources/text/help/r/export.rtf

Bones here.. I'm just going to create pull requests for the help where I see typo's etc... hope thats ok.

Clarified the explanation and fixed a typo

---

TRSE.pro

Small patch to fix compilation on non-arm

Fix mac compile on non-arm

---

units/C64/gfx/bitmapgraphics.tru

removed depreciated ProcedureToPointer from bitmapgraphics unit

removed depreciated ProcedureToPointer from bitmapgraphics unit

---

resources/text/help/m/addresstable.rtf

Also added PET screen memory start address

Missing # in #addr

---

Publish/project_templates/pet_general/files/main.ras

Corrections

---

source/Compiler/systems/systempet.cpp
source/Compiler/systems/systempet.h

The Pet memory map to display as an overlay.

PET memory map details

---

source/Compiler/systems/systemnes.cpp
source/Compiler/systems/systemnes.h

NES Memory Map

---

resources/text/help/p/variables.rtf

Should be integer

---

source/PmmEdit/codeeditor.cpp

Fixes the automatic indent + end -adding if there already is "end" in the block.

Bugfix: Fix too many ends

---

mainwindow.cpp
mainwindow.h
mainwindow.ui
source/PmmEdit/codeeditor.cpp

Add menu-item to add include-files.
Also enable auto-indent support for include-files.

Add support for .inc files

---

source/PmmEdit/codeeditor.cpp

Nice bug in auto-end feature when file contained @ifdef and @endif, the indent also failed to insert "end". 
This fixes the issue.

Bugfix: Fix bug in indent

---

mainwindow.cpp
source/Compiler/parser.cpp
source/LeLib/util/cinifile.cpp
source/dialogprojectsettings.cpp
source/dialogprojectsettings.ui
source/trsedocuments/formraseditor.cpp

- Allow to choose the model (464, 664, 6128 or 6128 Plus)
- Allow to pass additional options (e.g "-O system.limit_speed=0 -O system.printer=1 -O file.printer_file=/tmp/cpc_printer.dat")

Add project settings for Amstrad CPC

---

Publish/tutorials/C64/Tutorials/language/04_screen_numbers.ras

I don't quite understand why (still reading through these tutorials), but this program won't work as intended without the # here.

setting the screen memory pointer requires #

---

source/Compiler/systems/systemtim.cpp

Fix for compiling on Linux and file permissions.

Small fix for Linux

---

units/TIM/system/graphics.tru
units/TIM/system/screen.tru
units/TIM/system/system.tru
units/TIM/system/tiles.tru
units/TIM/system/z80cpm.tru

Added comments so that help can be seen for functions.

Added /** **/ comments for TIM unit procedures

---

source/Compiler/systems/systemtim.cpp

I have added a code that would check if "copy_to_img" directory exists inside project directory, and if it does, copy anything from it into a generated floppy image.

Added custom files inside floppy image file for TIM

---

Publish/tutorials/TIM/tutorials/benchmark.tru
Publish/tutorials/TIM/tutorials/tut1-Hello.ras
Publish/tutorials/TIM/tutorials/tut14-File.ras
Publish/tutorials/TIM/tutorials/tut15-TPC.ras
Publish/tutorials/TIM/tutorials/tut16-fake-3d.ras
Publish/tutorials/TIM/tutorials/tut17-real-3d.ras
Publish/tutorials/TIM/tutorials/tut2-Screen.ras
Publish/tutorials/TIM/tutorials/tut3-Scroll.ras
Publish/tutorials/TIM/tutorials/tut5-Tiles1.ras
units/TIM/system/screen.tru
units/TIM/system/system.tru

Added FPS counter to TIM 3D examples, added possibility to clear with ClearBox(...) instead of Line(...)

Tim 3d benchmark

---

Publish/tutorials/TIM/tutorials/benchmark.tru
Publish/tutorials/TIM/tutorials/tut17-real-3d.ras

And a fix for benchmark, to display digits correctly (but, this might be a problem in TRSE)

Small update to 3D tutorial, to include all tried ways of clearing picture

---

units/cpu_specific/Z80/random.tru

Added functions for random byte, and two for setting the seed value.

Added three functions to Z80 Random module

---

mainwindow.cpp
source/Compiler/ast/node.h
source/Compiler/codegen/abstractcodegen.cpp
source/Compiler/codegen/abstractcodegen.h
source/Compiler/codegen/codegen_6502.cpp
source/Compiler/codegen/codegen_6809.cpp
source/Compiler/codegen/codegen_x86.cpp
source/Compiler/codegen/methods/methodsz80.cpp
source/Compiler/compilers/compiler.cpp
source/Compiler/compilers/compiler6502.cpp
source/Compiler/compilers/compilerarm.cpp
source/Compiler/compilers/compilerchip8.cpp
source/Compiler/compilers/compilerjdh8.cpp
source/Compiler/compilers/compilerm68k.cpp
source/Compiler/compilers/compilers1c88.cpp
source/Compiler/compilers/compilerz80.cpp
source/Compiler/errorhandler.cpp
source/Compiler/lexer.h

Meaning I made a lot of the members that didn't need to be public protected or private. 
This should make it a lot easier to make custom Codegens because you don't have to worry about what all the public members do and should you set them.

Privatized the AST and Codegen

---

source/formhelp.cpp

I still did not get help for "for" when I pressed F1 on it, so I changed the logic a bit more, in line with the latest change.

A better help

---

units/TIM/system/file.tru
units/TIM/system/screen.tru

I have made a small update to TIM-011 libraries, I used those in tetris code.

Extended libraries, used for TimTris
